### ISSUE TITLE
TypeError: Converting py args to operator properties: : keyword "use_proportional_edit" unrecognized

### ISSUE THREAD

**Issue by dekiesel** [lcgamboa/sh3dtoblender#1]
Hi and thanks for this repo!

On 2.92.0 I am getting this error when importing my .zip.
```
Warning: No mesh data to join
Python: Traceback (most recent call last):
  File "/sh3d_xml_to_blender_2.80.py", line 187, in execute
  File "/home/kiesel/blender-2.92.0-linux64/2.92/scripts/modules/bpy/ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "use_proportional_edit" unrecognized

location: <unknown location>:-1
```

Is there anything I can do to fix this?

Thank you for your assistance!

/edit: In 2.8.13 blender crashes when importing. Ill see if I can find the 2.80 version

**Comment by lcgamboa** [comment]
Hello dekiesel,

I use unstable Debian, in it the version of blender is 2.83.5.
Here it is running smoothly. It may be something specific to your .zip file.
Apparently the script has a bug, opening the blender, the standard screen has a camera, a light and a selected cube. If the cube is not selected, the script does not work and gives an error. It may also be the cause of your problem. I haven't touched this script in a while.

If you want to send a file for me to test here I can try to fix it if I can reproduce the problem.
